name: chess
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.5=h4612cfd_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py313h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chess==1.11.2
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.4
      - lightning==2.5.3
      - lightning-utilities==0.15.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pillow==11.0.0
      - propcache==0.3.2
      - pytorch-lightning==2.5.3
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - sympy==1.13.3
      - tokenizers==0.21.4
      - torch==2.8.0+cu126
      - torchmetrics==1.8.1
      - torchvision==0.23.0+cu126
      - tqdm==4.67.1
      - transformers==4.55.3
      - triton==3.4.0
      - typing-extensions==4.12.2
      - urllib3==2.5.0
      - yarl==1.20.1
